### ISSUE TITLE
Matrix function definition is missing

### ISSUE THREAD

**Issue by Th3rdSergeevich** [aboood40091/ffl#2]
Most functions dedicated to matrix math (MTXOrtho, Mat34Concat, etc.) does not have a definition within the code or possible links to library that may contain those functions.

Is there any way to deduce these functions? Or have they been taken from the closed-source SDK?

**Comment by aboood40091** [comment]
These functions are all part of the Cafe SDK, and will not be decompiled for the `master` branch. The `master` branch assumes that you have the Cafe SDK headers or equivalent. For the actual `wut` branch, I used headers that map Cafe SDK functions to [WUT](https://github.com/devkitPro/wut) functions, which you can partially find [here](https://github.com/nw4f/G3d/tree/nsmbu-win-port/CafeSDKWrappers/cafe_wut), but still will not be enough to build since I didn't publish the mtx headers.

Alternatively, you can refer to the [nsmbu-win-port branch](https://github.com/aboood40091/ffl/tree/nsmbu-win-port), which is also buildable for Wii U using WUT but requires [RIO](https://github.com/aboood40091/RIO).

**Comment by Th3rdSergeevich** [comment]
I see. Thanks for clarifying!
